---
# role: ansible-role-samba-dc
# file: .travis.yml

language: python

python:
  - "3.9"

services: docker

branches:
  only:
    - main

env:
  jobs:
    - TOX_IMG="Arch"      TOX_ANSIBLE="{29,210}"
    - TOX_IMG="Debian"    TOX_ANSIBLE="{29,210}"
    - TOX_IMG="Fedora"    TOX_ANSIBLE="{29,210}"
    - TOX_IMG="Ubuntu"    TOX_ANSIBLE="{29,210}"

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install tox-travis

script:
  - tox
