---
# role: ansible-role-samba-dc
# file: .travis.yml

language: python

python:
  - "3.9"

services: docker

branches:
  only:
    - main

env:
  jobs:
    - TOX_IMG="Arch"      TOX_ANSIBLE="{29,210}"
    - TOX_IMG="Debian"    TOX_ANSIBLE="{29,210}"
    - TOX_IMG="Fedora"    TOX_ANSIBLE="{29,210}"
    - TOX_IMG="Ubuntu"    TOX_ANSIBLE="{29,210}"

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install tox-travis

script:
  - tox -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d .)-an${TOX_ANSIBLE}-${TOX_IMG}
  - rm -r .tox/py*/log/*
  - find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
