---
# role: ansible-role-samba-dc-dc
# file: tasks/resolv.yml

# This is only a basic resolv.conf setup, which can be overwritten e.g.
# by resolvconf, systemd-resolved, openresolv, etc...
# To permanently change this setting use another role or configure manually.
# Configuration of resolv.conf is not part of this role.
- name: "Resolver | Add nameserver 127.0.0.1 to /etc/resolv.conf"
  lineinfile:
    insertbefore: BOF
    line: nameserver 127.0.0.1
    path: /etc/resolv.conf

- name: "Resolver | Remove existing search entry from /etc/resolv.conf"
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    state: absent
    regexp: '^search'

- name: "Resolver | Add search entry for samba domain to /etc/resolv.conf"
  lineinfile:
    insertbefore: BOF
    line: "search {{ samba_dns_domain | lower }}"
    path: /etc/resolv.conf
