---
# role: ansible-role-samba-dc
# file: molecule/resources/playbooks/verify.yml

- name: Verify
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: "DNS | Verify netlogon and sysvol shares"
      command: "smbclient -L localhost -N"
      changed_when: false
      register: samba_dc_check_shares

    - name: "DNS | Verify _ldap SRV record"
      command: "host -t SRV _ldap._tcp.{{ samba_dc_dns_domain | lower }}."
      changed_when: false
      register: samba_dc_check_ldap_srv

    - name: "DNS | Verify _kerberos SRV record"
      command: "host -t SRV _kerberos._udp.{{ samba_dc_dns_domain | lower }}."
      changed_when: false
      register: samba_dc_check_kerberos_srv

    - name: "DNS | Verify host A record"
      command: "host -t A {{ ansible_hostname }}.{{ samba_dc_dns_domain | lower }}."
      changed_when: false
      register: samba_dc_check_host_a

    - name: "Kerberos | Verify kerberos authentication"
      shell: |
        kinit administrator<<EOC
        {{ samba_dc_admin_password }}
        EOC
        klist
      changed_when: false
      register: samba_dc_check_kerberos

    - name: "Assertions"
      assert:
        that:
          - "'netlogon' in samba_dc_check_shares.stdout"
          - "'sysvol' in samba_dc_check_shares.stdout"
          - "'has SRV record' in samba_dc_check_ldap_srv.stdout"
          - "'has SRV record' in samba_dc_check_kerberos_srv.stdout"
          - "'has address' in samba_dc_check_host_a.stdout"
          - "'Expires' and samba_dc_dns_domain | upper in samba_dc_check_kerberos.stdout"
