---
# role: ansible-role-dc-samba-dc
# file: molecule/tox/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "dctox"
    image: ${MOLECULE_IMG:-"jam82/molecule-debian:11"}
    command: ${MOLECULE_IMG_CMD:-""}
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        common_role_enabled: true
        hosts_role_enabled: true
        hosts_ip_static: true
        hosts_domain: 'samdom.localdomain'
        hosts_role_enable: true
        samba_dc_role_enabled: true
        samba_dc_domain_provision: true
        samba_dc_dns_domain: 'samdom.localdomain'
        samba_dc_site: 'MySite'
        samba_dc_admin_password: "Chang3MeN0w!"
        samba_dc_dc_no_log: false
verifier:
  name: ansible
